[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="utils" type="info.maila.baseapp.config.FreemarkerSharedVariablesConfig.FreemarkerUtils" --]
[#-- @ftlvariable name="httpRequest" type="jakarta.servlet.http.HttpServletRequest" --]
[#-- @ftlvariable name="httpResponse" type="jakarta.servlet.http.HttpServletResponse" --]
[#-- @ftlvariable name="rc" type="org.springframework.web.servlet.support.RequestContext" --]
[#-- @ftlvariable name="statics" type="java.util.Map<java.lang.String, java.lang.Object>" --]
[#import '/templates/components/page.ftlh' as p]
[#import '/templates/components/table.ftlh' as t]
[#import '/templates/components/form.ftlh' as f]
[#import '/templates/components/button.ftlh' as b]
[#import '/templates/components/functions.ftlh' as fun]