<div class="btn-group btn-group-sm theme-switch" role="group"
     aria-label="Switch theme">
    <button id="theme-dark" type="button" class="btn btn-outline-secondary">
        <i class="bi bi-moon"></i>
    </button>
    <button id="theme-light" type="button" class="btn btn-outline-secondary">
        <i class="bi bi-sun"></i>
    </button>
    <button id="theme-system" type="button" class="btn btn-outline-secondary">
        <i class="bi bi-display"></i>
    </button>
</div>