package info.maila.baseapp.domain.music

import jakarta.validation.constraints.NotNull
import org.springframework.data.annotation.Id
import org.springframework.data.annotation.Version
import org.springframework.data.relational.core.mapping.Table

@Table(name = "track", schema = "baseapp")
data class Track(
    @Id
    val id: Long? = null,
    @Version
    val dbVersion: Int? = null,
    @NotNull
    val path: String? = null,
    val acoustidFingerprint: String? = null,
    val acoustidId: String? = null,
    val album: String? = null,
    val albumArtist: String? = null,
    val albumArtistSort: String? = null,
    val albumArtists: String? = null,
    val albumArtistsSort: String? = null,
    val albumSort: String? = null,
    val albumYear: String? = null,
    val amazonId: String? = null,
    val arranger: String? = null,
    val arrangerSort: String? = null,
    val artist: String? = null,
    val artists: String? = null,
    val artistsSort: String? = null,
    val artistSort: String? = null,
    val barcode: String? = null,
    val bpm: String? = null,
    val catalogNo: String? = null,
    val classicalCatalog: String? = null,
    val classicalNickname: String? = null,
    val choir: String? = null,
    val choirSort: String? = null,
    val comment: String? = null,
    val composer: String? = null,
    val composerSort: String? = null,
    val conductor: String? = null,
    val conductorSort: String? = null,
    val copyright: String? = null,
    val country: String? = null,
    val coverArt: String? = null,
    val custom1: String? = null,
    val custom2: String? = null,
    val custom3: String? = null,
    val custom4: String? = null,
    val custom5: String? = null,
    val discNo: String? = null,
    val discSubtitle: String? = null,
    val discTotal: String? = null,
    val djmixer: String? = null,
    val djmixerSort: String? = null,
    val encoder: String? = null,
    val engineer: String? = null,
    val engineerSort: String? = null,
    val ensemble: String? = null,
    val ensembleSort: String? = null,
    val fbpm: String? = null,
    val genre: String? = null,
    val group: String? = null,
    val grouping: String? = null,
    val instrument: String? = null,
    val involvedpeople: String? = null,
    val ipi: String? = null,
    val isrc: String? = null,
    val iswc: String? = null,
    val isClassical: String? = null,
    val isGreatestHits: String? = null,
    val isHd: String? = null,
    val isLive: String? = null,
    val isSoundtrack: String? = null,
    val isCompilation: String? = null,
    val itunesGrouping: String? = null,
    val jaikozId: String? = null,
    val key: String? = null,
    val language: String? = null,
    val lyricist: String? = null,
    val lyricistSort: String? = null,
    val lyrics: String? = null,
    val media: String? = null,
    val mixer: String? = null,
    val mixerSort: String? = null,
    val mood: String? = null,
    val moodAcoustic: String? = null,
    val moodAggressive: String? = null,
    val moodArousal: String? = null,
    val moodDanceability: String? = null,
    val moodElectronic: String? = null,
    val moodHappy: String? = null,
    val moodInstrumental: String? = null,
    val moodParty: String? = null,
    val moodRelaxed: String? = null,
    val moodSad: String? = null,
    val moodValence: String? = null,
    val movement: String? = null,
    val movementNo: String? = null,
    val movementTotal: String? = null,
    val musicbrainzArtistid: String? = null,
    val musicbrainzDiscId: String? = null,
    val musicbrainzOriginalReleaseId: String? = null,
    val musicbrainzRecordingWork: String? = null,
    val musicbrainzRecordingWorkId: String? = null,
    val musicbrainzReleaseartistid: String? = null,
    val musicbrainzReleaseid: String? = null,
    val musicbrainzReleaseCountry: String? = null,
    val musicbrainzReleaseGroupId: String? = null,
    val musicbrainzReleaseStatus: String? = null,
    val musicbrainzReleaseTrackId: String? = null,
    val musicbrainzReleaseType: String? = null,
    val musicbrainzTrackId: String? = null,
    val musicbrainzWork: String? = null,
    val musicbrainzWorkId: String? = null,
    val musicbrainzWorkPartLevel1: String? = null,
    val musicbrainzWorkPartLevel1Id: String? = null,
    val musicbrainzWorkPartLevel1Type: String? = null,
    val musicbrainzWorkPartLevel2: String? = null,
    val musicbrainzWorkPartLevel2Id: String? = null,
    val musicbrainzWorkPartLevel2Type: String? = null,
    val musicbrainzWorkPartLevel3: String? = null,
    val musicbrainzWorkPartLevel3Id: String? = null,
    val musicbrainzWorkPartLevel3Type: String? = null,
    val musicbrainzWorkPartLevel4: String? = null,
    val musicbrainzWorkPartLevel4Id: String? = null,
    val musicbrainzWorkPartLevel4Type: String? = null,
    val musicbrainzWorkPartLevel5: String? = null,
    val musicbrainzWorkPartLevel5Id: String? = null,
    val musicbrainzWorkPartLevel5Type: String? = null,
    val musicbrainzWorkPartLevel6: String? = null,
    val musicbrainzWorkPartLevel6Id: String? = null,
    val musicbrainzWorkPartLevel6Type: String? = null,
    val musicipId: String? = null,
    val occasion: String? = null,
    val opus: String? = null,
    val orchestra: String? = null,
    val orchestraSort: String? = null,
    val originalAlbum: String? = null,
    val originalreleasedate: String? = null,
    val originalArtist: String? = null,
    val originalLyricist: String? = null,
    val originalYear: String? = null,
    val overallWork: String? = null,
    val part: String? = null,
    val partNumber: String? = null,
    val partType: String? = null,
    val performer: String? = null,
    val performerName: String? = null,
    val performerNameSort: String? = null,
    val period: String? = null,
    val producer: String? = null,
    val producerSort: String? = null,
    val quality: String? = null,
    val ranking: String? = null,
    val rating: String? = null,
    val recordLabel: String? = null,
    val recordingdate: String? = null,
    val recordingstartdate: String? = null,
    val recordingenddate: String? = null,
    val recordinglocation: String? = null,
    val remixer: String? = null,
    val roonalbumtag: String? = null,
    val roontracktag: String? = null,
    val section: String? = null,
    val script: String? = null,
    val singleDiscTrackNo: String? = null,
    val songkongId: String? = null,
    val subtitle: String? = null,
    val tags: String? = null,
    val tempo: String? = null,
    val timbre: String? = null,
    @NotNull
    val title: String? = null,
    val titleSort: String? = null,
    val titleMovement: String? = null,
    val tonality: String? = null,
    val track: String? = null,
    val trackTotal: String? = null,
    val urlDiscogsArtistSite: String? = null,
    val urlDiscogsReleaseSite: String? = null,
    val urlLyricsSite: String? = null,
    val urlOfficialArtistSite: String? = null,
    val urlOfficialReleaseSite: String? = null,
    val urlWikipediaArtistSite: String? = null,
    val urlWikipediaReleaseSite: String? = null,
    val work: String? = null,
    val workType: String? = null,
    val year: String? = null,
    val version: String? = null
) {

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Track

        if (id != other.id) return false
        if (dbVersion != other.dbVersion) return false
        if (path != other.path) return false
        if (acoustidFingerprint != other.acoustidFingerprint) return false
        if (acoustidId != other.acoustidId) return false
        if (album != other.album) return false
        if (albumArtist != other.albumArtist) return false
        if (albumArtistSort != other.albumArtistSort) return false
        if (albumArtists != other.albumArtists) return false
        if (albumArtistsSort != other.albumArtistsSort) return false
        if (albumSort != other.albumSort) return false
        if (albumYear != other.albumYear) return false
        if (amazonId != other.amazonId) return false
        if (arranger != other.arranger) return false
        if (arrangerSort != other.arrangerSort) return false
        if (artist != other.artist) return false
        if (artists != other.artists) return false
        if (artistsSort != other.artistsSort) return false
        if (artistSort != other.artistSort) return false
        if (barcode != other.barcode) return false
        if (bpm != other.bpm) return false
        if (catalogNo != other.catalogNo) return false
        if (classicalCatalog != other.classicalCatalog) return false
        if (classicalNickname != other.classicalNickname) return false
        if (choir != other.choir) return false
        if (choirSort != other.choirSort) return false
        if (comment != other.comment) return false
        if (composer != other.composer) return false
        if (composerSort != other.composerSort) return false
        if (conductor != other.conductor) return false
        if (conductorSort != other.conductorSort) return false
        if (copyright != other.copyright) return false
        if (country != other.country) return false
        if (coverArt != other.coverArt) return false
        if (custom1 != other.custom1) return false
        if (custom2 != other.custom2) return false
        if (custom3 != other.custom3) return false
        if (custom4 != other.custom4) return false
        if (custom5 != other.custom5) return false
        if (discNo != other.discNo) return false
        if (discSubtitle != other.discSubtitle) return false
        if (discTotal != other.discTotal) return false
        if (djmixer != other.djmixer) return false
        if (djmixerSort != other.djmixerSort) return false
        if (encoder != other.encoder) return false
        if (engineer != other.engineer) return false
        if (engineerSort != other.engineerSort) return false
        if (ensemble != other.ensemble) return false
        if (ensembleSort != other.ensembleSort) return false
        if (fbpm != other.fbpm) return false
        if (genre != other.genre) return false
        if (group != other.group) return false
        if (grouping != other.grouping) return false
        if (instrument != other.instrument) return false
        if (involvedpeople != other.involvedpeople) return false
        if (ipi != other.ipi) return false
        if (isrc != other.isrc) return false
        if (iswc != other.iswc) return false
        if (isClassical != other.isClassical) return false
        if (isGreatestHits != other.isGreatestHits) return false
        if (isHd != other.isHd) return false
        if (isLive != other.isLive) return false
        if (isSoundtrack != other.isSoundtrack) return false
        if (isCompilation != other.isCompilation) return false
        if (itunesGrouping != other.itunesGrouping) return false
        if (jaikozId != other.jaikozId) return false
        if (key != other.key) return false
        if (language != other.language) return false
        if (lyricist != other.lyricist) return false
        if (lyricistSort != other.lyricistSort) return false
        if (lyrics != other.lyrics) return false
        if (media != other.media) return false
        if (mixer != other.mixer) return false
        if (mixerSort != other.mixerSort) return false
        if (mood != other.mood) return false
        if (moodAcoustic != other.moodAcoustic) return false
        if (moodAggressive != other.moodAggressive) return false
        if (moodArousal != other.moodArousal) return false
        if (moodDanceability != other.moodDanceability) return false
        if (moodElectronic != other.moodElectronic) return false
        if (moodHappy != other.moodHappy) return false
        if (moodInstrumental != other.moodInstrumental) return false
        if (moodParty != other.moodParty) return false
        if (moodRelaxed != other.moodRelaxed) return false
        if (moodSad != other.moodSad) return false
        if (moodValence != other.moodValence) return false
        if (movement != other.movement) return false
        if (movementNo != other.movementNo) return false
        if (movementTotal != other.movementTotal) return false
        if (musicbrainzArtistid != other.musicbrainzArtistid) return false
        if (musicbrainzDiscId != other.musicbrainzDiscId) return false
        if (musicbrainzOriginalReleaseId != other.musicbrainzOriginalReleaseId) return false
        if (musicbrainzRecordingWork != other.musicbrainzRecordingWork) return false
        if (musicbrainzRecordingWorkId != other.musicbrainzRecordingWorkId) return false
        if (musicbrainzReleaseartistid != other.musicbrainzReleaseartistid) return false
        if (musicbrainzReleaseid != other.musicbrainzReleaseid) return false
        if (musicbrainzReleaseCountry != other.musicbrainzReleaseCountry) return false
        if (musicbrainzReleaseGroupId != other.musicbrainzReleaseGroupId) return false
        if (musicbrainzReleaseStatus != other.musicbrainzReleaseStatus) return false
        if (musicbrainzReleaseTrackId != other.musicbrainzReleaseTrackId) return false
        if (musicbrainzReleaseType != other.musicbrainzReleaseType) return false
        if (musicbrainzTrackId != other.musicbrainzTrackId) return false
        if (musicbrainzWork != other.musicbrainzWork) return false
        if (musicbrainzWorkId != other.musicbrainzWorkId) return false
        if (musicbrainzWorkPartLevel1 != other.musicbrainzWorkPartLevel1) return false
        if (musicbrainzWorkPartLevel1Id != other.musicbrainzWorkPartLevel1Id) return false
        if (musicbrainzWorkPartLevel1Type != other.musicbrainzWorkPartLevel1Type) return false
        if (musicbrainzWorkPartLevel2 != other.musicbrainzWorkPartLevel2) return false
        if (musicbrainzWorkPartLevel2Id != other.musicbrainzWorkPartLevel2Id) return false
        if (musicbrainzWorkPartLevel2Type != other.musicbrainzWorkPartLevel2Type) return false
        if (musicbrainzWorkPartLevel3 != other.musicbrainzWorkPartLevel3) return false
        if (musicbrainzWorkPartLevel3Id != other.musicbrainzWorkPartLevel3Id) return false
        if (musicbrainzWorkPartLevel3Type != other.musicbrainzWorkPartLevel3Type) return false
        if (musicbrainzWorkPartLevel4 != other.musicbrainzWorkPartLevel4) return false
        if (musicbrainzWorkPartLevel4Id != other.musicbrainzWorkPartLevel4Id) return false
        if (musicbrainzWorkPartLevel4Type != other.musicbrainzWorkPartLevel4Type) return false
        if (musicbrainzWorkPartLevel5 != other.musicbrainzWorkPartLevel5) return false
        if (musicbrainzWorkPartLevel5Id != other.musicbrainzWorkPartLevel5Id) return false
        if (musicbrainzWorkPartLevel5Type != other.musicbrainzWorkPartLevel5Type) return false
        if (musicbrainzWorkPartLevel6 != other.musicbrainzWorkPartLevel6) return false
        if (musicbrainzWorkPartLevel6Id != other.musicbrainzWorkPartLevel6Id) return false
        if (musicbrainzWorkPartLevel6Type != other.musicbrainzWorkPartLevel6Type) return false
        if (musicipId != other.musicipId) return false
        if (occasion != other.occasion) return false
        if (opus != other.opus) return false
        if (orchestra != other.orchestra) return false
        if (orchestraSort != other.orchestraSort) return false
        if (originalAlbum != other.originalAlbum) return false
        if (originalreleasedate != other.originalreleasedate) return false
        if (originalArtist != other.originalArtist) return false
        if (originalLyricist != other.originalLyricist) return false
        if (originalYear != other.originalYear) return false
        if (overallWork != other.overallWork) return false
        if (part != other.part) return false
        if (partNumber != other.partNumber) return false
        if (partType != other.partType) return false
        if (performer != other.performer) return false
        if (performerName != other.performerName) return false
        if (performerNameSort != other.performerNameSort) return false
        if (period != other.period) return false
        if (producer != other.producer) return false
        if (producerSort != other.producerSort) return false
        if (quality != other.quality) return false
        if (ranking != other.ranking) return false
        if (rating != other.rating) return false
        if (recordLabel != other.recordLabel) return false
        if (recordingdate != other.recordingdate) return false
        if (recordingstartdate != other.recordingstartdate) return false
        if (recordingenddate != other.recordingenddate) return false
        if (recordinglocation != other.recordinglocation) return false
        if (remixer != other.remixer) return false
        if (roonalbumtag != other.roonalbumtag) return false
        if (roontracktag != other.roontracktag) return false
        if (section != other.section) return false
        if (script != other.script) return false
        if (singleDiscTrackNo != other.singleDiscTrackNo) return false
        if (songkongId != other.songkongId) return false
        if (subtitle != other.subtitle) return false
        if (tags != other.tags) return false
        if (tempo != other.tempo) return false
        if (timbre != other.timbre) return false
        if (title != other.title) return false
        if (titleSort != other.titleSort) return false
        if (titleMovement != other.titleMovement) return false
        if (tonality != other.tonality) return false
        if (track != other.track) return false
        if (trackTotal != other.trackTotal) return false
        if (urlDiscogsArtistSite != other.urlDiscogsArtistSite) return false
        if (urlDiscogsReleaseSite != other.urlDiscogsReleaseSite) return false
        if (urlLyricsSite != other.urlLyricsSite) return false
        if (urlOfficialArtistSite != other.urlOfficialArtistSite) return false
        if (urlOfficialReleaseSite != other.urlOfficialReleaseSite) return false
        if (urlWikipediaArtistSite != other.urlWikipediaArtistSite) return false
        if (urlWikipediaReleaseSite != other.urlWikipediaReleaseSite) return false
        if (work != other.work) return false
        if (workType != other.workType) return false
        if (year != other.year) return false
        if (version != other.version) return false

        return true
    }

    override fun hashCode(): Int {
        var result = id?.hashCode() ?: 0
        result = 31 * result + (dbVersion ?: 0)
        result = 31 * result + (path?.hashCode() ?: 0)
        result = 31 * result + (acoustidFingerprint?.hashCode() ?: 0)
        result = 31 * result + (acoustidId?.hashCode() ?: 0)
        result = 31 * result + (album?.hashCode() ?: 0)
        result = 31 * result + (albumArtist?.hashCode() ?: 0)
        result = 31 * result + (albumArtistSort?.hashCode() ?: 0)
        result = 31 * result + (albumArtists?.hashCode() ?: 0)
        result = 31 * result + (albumArtistsSort?.hashCode() ?: 0)
        result = 31 * result + (albumSort?.hashCode() ?: 0)
        result = 31 * result + (albumYear?.hashCode() ?: 0)
        result = 31 * result + (amazonId?.hashCode() ?: 0)
        result = 31 * result + (arranger?.hashCode() ?: 0)
        result = 31 * result + (arrangerSort?.hashCode() ?: 0)
        result = 31 * result + (artist?.hashCode() ?: 0)
        result = 31 * result + (artists?.hashCode() ?: 0)
        result = 31 * result + (artistsSort?.hashCode() ?: 0)
        result = 31 * result + (artistSort?.hashCode() ?: 0)
        result = 31 * result + (barcode?.hashCode() ?: 0)
        result = 31 * result + (bpm?.hashCode() ?: 0)
        result = 31 * result + (catalogNo?.hashCode() ?: 0)
        result = 31 * result + (classicalCatalog?.hashCode() ?: 0)
        result = 31 * result + (classicalNickname?.hashCode() ?: 0)
        result = 31 * result + (choir?.hashCode() ?: 0)
        result = 31 * result + (choirSort?.hashCode() ?: 0)
        result = 31 * result + (comment?.hashCode() ?: 0)
        result = 31 * result + (composer?.hashCode() ?: 0)
        result = 31 * result + (composerSort?.hashCode() ?: 0)
        result = 31 * result + (conductor?.hashCode() ?: 0)
        result = 31 * result + (conductorSort?.hashCode() ?: 0)
        result = 31 * result + (copyright?.hashCode() ?: 0)
        result = 31 * result + (country?.hashCode() ?: 0)
        result = 31 * result + (coverArt?.hashCode() ?: 0)
        result = 31 * result + (custom1?.hashCode() ?: 0)
        result = 31 * result + (custom2?.hashCode() ?: 0)
        result = 31 * result + (custom3?.hashCode() ?: 0)
        result = 31 * result + (custom4?.hashCode() ?: 0)
        result = 31 * result + (custom5?.hashCode() ?: 0)
        result = 31 * result + (discNo?.hashCode() ?: 0)
        result = 31 * result + (discSubtitle?.hashCode() ?: 0)
        result = 31 * result + (discTotal?.hashCode() ?: 0)
        result = 31 * result + (djmixer?.hashCode() ?: 0)
        result = 31 * result + (djmixerSort?.hashCode() ?: 0)
        result = 31 * result + (encoder?.hashCode() ?: 0)
        result = 31 * result + (engineer?.hashCode() ?: 0)
        result = 31 * result + (engineerSort?.hashCode() ?: 0)
        result = 31 * result + (ensemble?.hashCode() ?: 0)
        result = 31 * result + (ensembleSort?.hashCode() ?: 0)
        result = 31 * result + (fbpm?.hashCode() ?: 0)
        result = 31 * result + (genre?.hashCode() ?: 0)
        result = 31 * result + (group?.hashCode() ?: 0)
        result = 31 * result + (grouping?.hashCode() ?: 0)
        result = 31 * result + (instrument?.hashCode() ?: 0)
        result = 31 * result + (involvedpeople?.hashCode() ?: 0)
        result = 31 * result + (ipi?.hashCode() ?: 0)
        result = 31 * result + (isrc?.hashCode() ?: 0)
        result = 31 * result + (iswc?.hashCode() ?: 0)
        result = 31 * result + (isClassical?.hashCode() ?: 0)
        result = 31 * result + (isGreatestHits?.hashCode() ?: 0)
        result = 31 * result + (isHd?.hashCode() ?: 0)
        result = 31 * result + (isLive?.hashCode() ?: 0)
        result = 31 * result + (isSoundtrack?.hashCode() ?: 0)
        result = 31 * result + (isCompilation?.hashCode() ?: 0)
        result = 31 * result + (itunesGrouping?.hashCode() ?: 0)
        result = 31 * result + (jaikozId?.hashCode() ?: 0)
        result = 31 * result + (key?.hashCode() ?: 0)
        result = 31 * result + (language?.hashCode() ?: 0)
        result = 31 * result + (lyricist?.hashCode() ?: 0)
        result = 31 * result + (lyricistSort?.hashCode() ?: 0)
        result = 31 * result + (lyrics?.hashCode() ?: 0)
        result = 31 * result + (media?.hashCode() ?: 0)
        result = 31 * result + (mixer?.hashCode() ?: 0)
        result = 31 * result + (mixerSort?.hashCode() ?: 0)
        result = 31 * result + (mood?.hashCode() ?: 0)
        result = 31 * result + (moodAcoustic?.hashCode() ?: 0)
        result = 31 * result + (moodAggressive?.hashCode() ?: 0)
        result = 31 * result + (moodArousal?.hashCode() ?: 0)
        result = 31 * result + (moodDanceability?.hashCode() ?: 0)
        result = 31 * result + (moodElectronic?.hashCode() ?: 0)
        result = 31 * result + (moodHappy?.hashCode() ?: 0)
        result = 31 * result + (moodInstrumental?.hashCode() ?: 0)
        result = 31 * result + (moodParty?.hashCode() ?: 0)
        result = 31 * result + (moodRelaxed?.hashCode() ?: 0)
        result = 31 * result + (moodSad?.hashCode() ?: 0)
        result = 31 * result + (moodValence?.hashCode() ?: 0)
        result = 31 * result + (movement?.hashCode() ?: 0)
        result = 31 * result + (movementNo?.hashCode() ?: 0)
        result = 31 * result + (movementTotal?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzArtistid?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzDiscId?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzOriginalReleaseId?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzRecordingWork?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzRecordingWorkId?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzReleaseartistid?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzReleaseid?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzReleaseCountry?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzReleaseGroupId?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzReleaseStatus?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzReleaseTrackId?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzReleaseType?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzTrackId?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzWork?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzWorkId?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzWorkPartLevel1?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzWorkPartLevel1Id?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzWorkPartLevel1Type?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzWorkPartLevel2?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzWorkPartLevel2Id?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzWorkPartLevel2Type?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzWorkPartLevel3?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzWorkPartLevel3Id?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzWorkPartLevel3Type?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzWorkPartLevel4?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzWorkPartLevel4Id?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzWorkPartLevel4Type?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzWorkPartLevel5?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzWorkPartLevel5Id?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzWorkPartLevel5Type?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzWorkPartLevel6?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzWorkPartLevel6Id?.hashCode() ?: 0)
        result = 31 * result + (musicbrainzWorkPartLevel6Type?.hashCode() ?: 0)
        result = 31 * result + (musicipId?.hashCode() ?: 0)
        result = 31 * result + (occasion?.hashCode() ?: 0)
        result = 31 * result + (opus?.hashCode() ?: 0)
        result = 31 * result + (orchestra?.hashCode() ?: 0)
        result = 31 * result + (orchestraSort?.hashCode() ?: 0)
        result = 31 * result + (originalAlbum?.hashCode() ?: 0)
        result = 31 * result + (originalreleasedate?.hashCode() ?: 0)
        result = 31 * result + (originalArtist?.hashCode() ?: 0)
        result = 31 * result + (originalLyricist?.hashCode() ?: 0)
        result = 31 * result + (originalYear?.hashCode() ?: 0)
        result = 31 * result + (overallWork?.hashCode() ?: 0)
        result = 31 * result + (part?.hashCode() ?: 0)
        result = 31 * result + (partNumber?.hashCode() ?: 0)
        result = 31 * result + (partType?.hashCode() ?: 0)
        result = 31 * result + (performer?.hashCode() ?: 0)
        result = 31 * result + (performerName?.hashCode() ?: 0)
        result = 31 * result + (performerNameSort?.hashCode() ?: 0)
        result = 31 * result + (period?.hashCode() ?: 0)
        result = 31 * result + (producer?.hashCode() ?: 0)
        result = 31 * result + (producerSort?.hashCode() ?: 0)
        result = 31 * result + (quality?.hashCode() ?: 0)
        result = 31 * result + (ranking?.hashCode() ?: 0)
        result = 31 * result + (rating?.hashCode() ?: 0)
        result = 31 * result + (recordLabel?.hashCode() ?: 0)
        result = 31 * result + (recordingdate?.hashCode() ?: 0)
        result = 31 * result + (recordingstartdate?.hashCode() ?: 0)
        result = 31 * result + (recordingenddate?.hashCode() ?: 0)
        result = 31 * result + (recordinglocation?.hashCode() ?: 0)
        result = 31 * result + (remixer?.hashCode() ?: 0)
        result = 31 * result + (roonalbumtag?.hashCode() ?: 0)
        result = 31 * result + (roontracktag?.hashCode() ?: 0)
        result = 31 * result + (section?.hashCode() ?: 0)
        result = 31 * result + (script?.hashCode() ?: 0)
        result = 31 * result + (singleDiscTrackNo?.hashCode() ?: 0)
        result = 31 * result + (songkongId?.hashCode() ?: 0)
        result = 31 * result + (subtitle?.hashCode() ?: 0)
        result = 31 * result + (tags?.hashCode() ?: 0)
        result = 31 * result + (tempo?.hashCode() ?: 0)
        result = 31 * result + (timbre?.hashCode() ?: 0)
        result = 31 * result + (title?.hashCode() ?: 0)
        result = 31 * result + (titleSort?.hashCode() ?: 0)
        result = 31 * result + (titleMovement?.hashCode() ?: 0)
        result = 31 * result + (tonality?.hashCode() ?: 0)
        result = 31 * result + (track?.hashCode() ?: 0)
        result = 31 * result + (trackTotal?.hashCode() ?: 0)
        result = 31 * result + (urlDiscogsArtistSite?.hashCode() ?: 0)
        result = 31 * result + (urlDiscogsReleaseSite?.hashCode() ?: 0)
        result = 31 * result + (urlLyricsSite?.hashCode() ?: 0)
        result = 31 * result + (urlOfficialArtistSite?.hashCode() ?: 0)
        result = 31 * result + (urlOfficialReleaseSite?.hashCode() ?: 0)
        result = 31 * result + (urlWikipediaArtistSite?.hashCode() ?: 0)
        result = 31 * result + (urlWikipediaReleaseSite?.hashCode() ?: 0)
        result = 31 * result + (work?.hashCode() ?: 0)
        result = 31 * result + (workType?.hashCode() ?: 0)
        result = 31 * result + (year?.hashCode() ?: 0)
        result = 31 * result + (version?.hashCode() ?: 0)
        return result
    }

}