CREATE SEQUENCE IF NOT EXISTS baseapp.track_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE IF NOT EXISTS baseapp.track
(
    id                                INT  NOT NULL DEFAULT nextval('baseapp.track_id_seq') PRIMARY KEY,
    db_version                        INT  NOT NULL DEFAULT 1,

    path                              TEXT NOT NULL UNIQUE,

    encoding_type                     TEXT,
    bit_rate                          INT,
    sample_rate                       INT,
    format                            TEXT,
    channels                          TEXT,
    is_variable_bit_rate              BOOLEAN,
    track_length                      DOUBLE PRECISION,
    bits_per_sample                   INT,
    is_lossless                       BOOLEAN,
    no_of_samples                     INT,

    acoustid_fingerprint              TEXT,
    acoustid_id                       TEXT,
    album                             TEXT,
    album_artist                      TEXT,
    album_artist_sort                 TEXT,
    album_artists                     TEXT,
    album_artists_sort                TEXT,
    album_sort                        TEXT,
    album_year                        TEXT,
    amazon_id                         TEXT,
    arranger                          TEXT,
    arranger_sort                     TEXT,
    artist                            TEXT,
    artists                           TEXT,
    artists_sort                      TEXT,
    artist_sort                       TEXT,
    barcode                           TEXT,
    bpm                               TEXT,
    catalog_no                        TEXT,
    classical_catalog                 TEXT,
    classical_nickname                TEXT,
    choir                             TEXT,
    choir_sort                        TEXT,
    comment                           TEXT,
    composer                          TEXT,
    composer_sort                     TEXT,
    conductor                         TEXT,
    conductor_sort                    TEXT,
    copyright                         TEXT,
    country                           TEXT,
    cover_art                         TEXT,
    custom1                           TEXT,
    custom2                           TEXT,
    custom3                           TEXT,
    custom4                           TEXT,
    custom5                           TEXT,
    disc_no                           TEXT,
    disc_subtitle                     TEXT,
    disc_total                        TEXT,
    djmixer                           TEXT,
    djmixer_sort                      TEXT,
    encoder                           TEXT,
    engineer                          TEXT,
    engineer_sort                     TEXT,
    ensemble                          TEXT,
    ensemble_sort                     TEXT,
    fbpm                              TEXT,
    genre                             TEXT,
    "group"                           TEXT,
    grouping                          TEXT,
    instrument                        TEXT,
    involvedpeople                    TEXT,
    ipi                               TEXT,
    isrc                              TEXT,
    iswc                              TEXT,
    is_classical                      TEXT,
    is_greatest_hits                  TEXT,
    is_hd                             TEXT,
    is_live                           TEXT,
    is_soundtrack                     TEXT,
    is_compilation                    TEXT,
    itunes_grouping                   TEXT,
    jaikoz_id                         TEXT,
    key                               TEXT,
    language                          TEXT,
    lyricist                          TEXT,
    lyricist_sort                     TEXT,
    lyrics                            TEXT,
    media                             TEXT,
    mixer                             TEXT,
    mixer_sort                        TEXT,
    mood                              TEXT,
    mood_acoustic                     TEXT,
    mood_aggressive                   TEXT,
    mood_arousal                      TEXT,
    mood_danceability                 TEXT,
    mood_electronic                   TEXT,
    mood_happy                        TEXT,
    mood_instrumental                 TEXT,
    mood_party                        TEXT,
    mood_relaxed                      TEXT,
    mood_sad                          TEXT,
    mood_valence                      TEXT,
    movement                          TEXT,
    movement_no                       TEXT,
    movement_total                    TEXT,
    musicbrainz_artistid              TEXT,
    musicbrainz_disc_id               TEXT,
    musicbrainz_original_release_id   TEXT,
    musicbrainz_recording_work        TEXT,
    musicbrainz_recording_work_id     TEXT,
    musicbrainz_releaseartistid       TEXT,
    musicbrainz_releaseid             TEXT,
    musicbrainz_release_country       TEXT,
    musicbrainz_release_group_id      TEXT,
    musicbrainz_release_status        TEXT,
    musicbrainz_release_track_id      TEXT,
    musicbrainz_release_type          TEXT,
    musicbrainz_track_id              TEXT,
    musicbrainz_work                  TEXT,
    musicbrainz_work_id               TEXT,
    musicbrainz_work_part_level1      TEXT,
    musicbrainz_work_part_level1_id   TEXT,
    musicbrainz_work_part_level1_type TEXT,
    musicbrainz_work_part_level2      TEXT,
    musicbrainz_work_part_level2_id   TEXT,
    musicbrainz_work_part_level2_type TEXT,
    musicbrainz_work_part_level3      TEXT,
    musicbrainz_work_part_level3_id   TEXT,
    musicbrainz_work_part_level3_type TEXT,
    musicbrainz_work_part_level4      TEXT,
    musicbrainz_work_part_level4_id   TEXT,
    musicbrainz_work_part_level4_type TEXT,
    musicbrainz_work_part_level5      TEXT,
    musicbrainz_work_part_level5_id   TEXT,
    musicbrainz_work_part_level5_type TEXT,
    musicbrainz_work_part_level6      TEXT,
    musicbrainz_work_part_level6_id   TEXT,
    musicbrainz_work_part_level6_type TEXT,
    musicip_id                        TEXT,
    occasion                          TEXT,
    opus                              TEXT,
    orchestra                         TEXT,
    orchestra_sort                    TEXT,
    original_album                    TEXT,
    originalreleasedate               TEXT,
    original_artist                   TEXT,
    original_lyricist                 TEXT,
    original_year                     TEXT,
    overall_work                      TEXT,
    part                              TEXT,
    part_number                       TEXT,
    part_type                         TEXT,
    performer                         TEXT,
    performer_name                    TEXT,
    performer_name_sort               TEXT,
    period                            TEXT,
    producer                          TEXT,
    producer_sort                     TEXT,
    quality                           TEXT,
    ranking                           TEXT,
    rating                            TEXT,
    record_label                      TEXT,
    recordingdate                     TEXT,
    recordingstartdate                TEXT,
    recordingenddate                  TEXT,
    recordinglocation                 TEXT,
    remixer                           TEXT,
    roonalbumtag                      TEXT,
    roontracktag                      TEXT,
    section                           TEXT,
    script                            TEXT,
    single_disc_track_no              TEXT,
    songkong_id                       TEXT,
    subtitle                          TEXT,
    tags                              TEXT,
    tempo                             TEXT,
    timbre                            TEXT,
    title                             TEXT NOT NULL,
    title_sort                        TEXT,
    title_movement                    TEXT,
    tonality                          TEXT,
    track                             TEXT,
    track_total                       TEXT,
    url_discogs_artist_site           TEXT,
    url_discogs_release_site          TEXT,
    url_lyrics_site                   TEXT,
    url_official_artist_site          TEXT,
    url_official_release_site         TEXT,
    url_wikipedia_artist_site         TEXT,
    url_wikipedia_release_site        TEXT,
    work                              TEXT,
    work_type                         TEXT,
    year                              TEXT,
    version                           TEXT
);

CREATE INDEX IF NOT EXISTS idx_track_title ON baseapp.track (title);
CREATE INDEX IF NOT EXISTS idx_track_title_sort ON baseapp.track (title_sort);
CREATE INDEX IF NOT EXISTS idx_track_album ON baseapp.track (album) WHERE album IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_track_album_sort ON baseapp.track (album_sort) WHERE album IS NOT NULL;